/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SizeGuideRouteImport } from './routes/size-guide'
import { Route as ReturnsRouteImport } from './routes/returns'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CareGuideRouteImport } from './routes/care-guide'
import { Route as AdminPreviewRouteImport } from './routes/admin-preview'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as AccountRouteRouteImport } from './routes/account/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShopIndexRouteImport } from './routes/shop/index'
import { Route as CheckoutIndexRouteImport } from './routes/checkout/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AccountIndexRouteImport } from './routes/account/index'
import { Route as ShopSlugRouteImport } from './routes/shop/$slug'
import { Route as DropSlugRouteImport } from './routes/drop/$slug'
import { Route as CheckoutSuccessRouteImport } from './routes/checkout/success'
import { Route as AuthSignUpRouteImport } from './routes/auth/sign-up'
import { Route as AuthSignInRouteImport } from './routes/auth/sign-in'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as AdminWebsiteLayoutRouteImport } from './routes/admin/website-layout'
import { Route as AdminThemeRouteImport } from './routes/admin/theme'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminSeoRouteImport } from './routes/admin/seo'
import { Route as AdminMediaRouteImport } from './routes/admin/media'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AccountPersonalRouteImport } from './routes/account/personal'
import { Route as AccountAddressesRouteImport } from './routes/account/addresses'
import { Route as AdminProductsIndexRouteImport } from './routes/admin/products/index'
import { Route as AdminDropsIndexRouteImport } from './routes/admin/drops/index'
import { Route as AccountOrdersIndexRouteImport } from './routes/account/orders/index'
import { Route as AdminProductsNewRouteImport } from './routes/admin/products/new'
import { Route as AdminProductsProductIdRouteImport } from './routes/admin/products/$productId'
import { Route as AdminDropsNewRouteImport } from './routes/admin/drops/new'
import { Route as AdminDropsDropIdRouteImport } from './routes/admin/drops/$dropId'
import { Route as AccountOrdersOrderIdRouteImport } from './routes/account/orders/$orderId'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SizeGuideRoute = SizeGuideRouteImport.update({
  id: '/size-guide',
  path: '/size-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const ReturnsRoute = ReturnsRouteImport.update({
  id: '/returns',
  path: '/returns',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CareGuideRoute = CareGuideRouteImport.update({
  id: '/care-guide',
  path: '/care-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPreviewRoute = AdminPreviewRouteImport.update({
  id: '/admin-preview',
  path: '/admin-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRouteRoute = AccountRouteRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopIndexRoute = ShopIndexRouteImport.update({
  id: '/shop/',
  path: '/shop/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutIndexRoute = CheckoutIndexRouteImport.update({
  id: '/checkout/',
  path: '/checkout/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccountRouteRoute,
} as any)
const ShopSlugRoute = ShopSlugRouteImport.update({
  id: '/shop/$slug',
  path: '/shop/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DropSlugRoute = DropSlugRouteImport.update({
  id: '/drop/$slug',
  path: '/drop/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutSuccessRoute = CheckoutSuccessRouteImport.update({
  id: '/checkout/success',
  path: '/checkout/success',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/auth/sign-up',
  path: '/auth/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/auth/sign-in',
  path: '/auth/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWebsiteLayoutRoute = AdminWebsiteLayoutRouteImport.update({
  id: '/website-layout',
  path: '/website-layout',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminThemeRoute = AdminThemeRouteImport.update({
  id: '/theme',
  path: '/theme',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSeoRoute = AdminSeoRouteImport.update({
  id: '/seo',
  path: '/seo',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminMediaRoute = AdminMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AccountPersonalRoute = AccountPersonalRouteImport.update({
  id: '/personal',
  path: '/personal',
  getParentRoute: () => AccountRouteRoute,
} as any)
const AccountAddressesRoute = AccountAddressesRouteImport.update({
  id: '/addresses',
  path: '/addresses',
  getParentRoute: () => AccountRouteRoute,
} as any)
const AdminProductsIndexRoute = AdminProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDropsIndexRoute = AdminDropsIndexRouteImport.update({
  id: '/drops/',
  path: '/drops/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AccountOrdersIndexRoute = AccountOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => AccountRouteRoute,
} as any)
const AdminProductsNewRoute = AdminProductsNewRouteImport.update({
  id: '/products/new',
  path: '/products/new',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminProductsProductIdRoute = AdminProductsProductIdRouteImport.update({
  id: '/products/$productId',
  path: '/products/$productId',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDropsNewRoute = AdminDropsNewRouteImport.update({
  id: '/drops/new',
  path: '/drops/new',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDropsDropIdRoute = AdminDropsDropIdRouteImport.update({
  id: '/drops/$dropId',
  path: '/drops/$dropId',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AccountOrdersOrderIdRoute = AccountOrdersOrderIdRouteImport.update({
  id: '/orders/$orderId',
  path: '/orders/$orderId',
  getParentRoute: () => AccountRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/admin-preview': typeof AdminPreviewRoute
  '/care-guide': typeof CareGuideRoute
  '/cart': typeof CartRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/returns': typeof ReturnsRoute
  '/size-guide': typeof SizeGuideRoute
  '/terms': typeof TermsRoute
  '/account/addresses': typeof AccountAddressesRoute
  '/account/personal': typeof AccountPersonalRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/seo': typeof AdminSeoRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/theme': typeof AdminThemeRoute
  '/admin/website-layout': typeof AdminWebsiteLayoutRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/drop/$slug': typeof DropSlugRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/checkout/': typeof CheckoutIndexRoute
  '/shop/': typeof ShopIndexRoute
  '/account/orders/$orderId': typeof AccountOrdersOrderIdRoute
  '/admin/drops/$dropId': typeof AdminDropsDropIdRoute
  '/admin/drops/new': typeof AdminDropsNewRoute
  '/admin/products/$productId': typeof AdminProductsProductIdRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/account/orders/': typeof AccountOrdersIndexRoute
  '/admin/drops/': typeof AdminDropsIndexRoute
  '/admin/products/': typeof AdminProductsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin-preview': typeof AdminPreviewRoute
  '/care-guide': typeof CareGuideRoute
  '/cart': typeof CartRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/returns': typeof ReturnsRoute
  '/size-guide': typeof SizeGuideRoute
  '/terms': typeof TermsRoute
  '/account/addresses': typeof AccountAddressesRoute
  '/account/personal': typeof AccountPersonalRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/seo': typeof AdminSeoRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/theme': typeof AdminThemeRoute
  '/admin/website-layout': typeof AdminWebsiteLayoutRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/drop/$slug': typeof DropSlugRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/account': typeof AccountIndexRoute
  '/admin': typeof AdminIndexRoute
  '/checkout': typeof CheckoutIndexRoute
  '/shop': typeof ShopIndexRoute
  '/account/orders/$orderId': typeof AccountOrdersOrderIdRoute
  '/admin/drops/$dropId': typeof AdminDropsDropIdRoute
  '/admin/drops/new': typeof AdminDropsNewRoute
  '/admin/products/$productId': typeof AdminProductsProductIdRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/account/orders': typeof AccountOrdersIndexRoute
  '/admin/drops': typeof AdminDropsIndexRoute
  '/admin/products': typeof AdminProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/admin-preview': typeof AdminPreviewRoute
  '/care-guide': typeof CareGuideRoute
  '/cart': typeof CartRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/returns': typeof ReturnsRoute
  '/size-guide': typeof SizeGuideRoute
  '/terms': typeof TermsRoute
  '/account/addresses': typeof AccountAddressesRoute
  '/account/personal': typeof AccountPersonalRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/seo': typeof AdminSeoRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/theme': typeof AdminThemeRoute
  '/admin/website-layout': typeof AdminWebsiteLayoutRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/drop/$slug': typeof DropSlugRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/checkout/': typeof CheckoutIndexRoute
  '/shop/': typeof ShopIndexRoute
  '/account/orders/$orderId': typeof AccountOrdersOrderIdRoute
  '/admin/drops/$dropId': typeof AdminDropsDropIdRoute
  '/admin/drops/new': typeof AdminDropsNewRoute
  '/admin/products/$productId': typeof AdminProductsProductIdRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/account/orders/': typeof AccountOrdersIndexRoute
  '/admin/drops/': typeof AdminDropsIndexRoute
  '/admin/products/': typeof AdminProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/about'
    | '/admin-preview'
    | '/care-guide'
    | '/cart'
    | '/contact'
    | '/privacy'
    | '/returns'
    | '/size-guide'
    | '/terms'
    | '/account/addresses'
    | '/account/personal'
    | '/admin/login'
    | '/admin/media'
    | '/admin/seo'
    | '/admin/settings'
    | '/admin/theme'
    | '/admin/website-layout'
    | '/auth/forgot-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/checkout/success'
    | '/drop/$slug'
    | '/shop/$slug'
    | '/account/'
    | '/admin/'
    | '/checkout/'
    | '/shop/'
    | '/account/orders/$orderId'
    | '/admin/drops/$dropId'
    | '/admin/drops/new'
    | '/admin/products/$productId'
    | '/admin/products/new'
    | '/account/orders/'
    | '/admin/drops/'
    | '/admin/products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin-preview'
    | '/care-guide'
    | '/cart'
    | '/contact'
    | '/privacy'
    | '/returns'
    | '/size-guide'
    | '/terms'
    | '/account/addresses'
    | '/account/personal'
    | '/admin/login'
    | '/admin/media'
    | '/admin/seo'
    | '/admin/settings'
    | '/admin/theme'
    | '/admin/website-layout'
    | '/auth/forgot-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/checkout/success'
    | '/drop/$slug'
    | '/shop/$slug'
    | '/account'
    | '/admin'
    | '/checkout'
    | '/shop'
    | '/account/orders/$orderId'
    | '/admin/drops/$dropId'
    | '/admin/drops/new'
    | '/admin/products/$productId'
    | '/admin/products/new'
    | '/account/orders'
    | '/admin/drops'
    | '/admin/products'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/admin'
    | '/about'
    | '/admin-preview'
    | '/care-guide'
    | '/cart'
    | '/contact'
    | '/privacy'
    | '/returns'
    | '/size-guide'
    | '/terms'
    | '/account/addresses'
    | '/account/personal'
    | '/admin/login'
    | '/admin/media'
    | '/admin/seo'
    | '/admin/settings'
    | '/admin/theme'
    | '/admin/website-layout'
    | '/auth/forgot-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/checkout/success'
    | '/drop/$slug'
    | '/shop/$slug'
    | '/account/'
    | '/admin/'
    | '/checkout/'
    | '/shop/'
    | '/account/orders/$orderId'
    | '/admin/drops/$dropId'
    | '/admin/drops/new'
    | '/admin/products/$productId'
    | '/admin/products/new'
    | '/account/orders/'
    | '/admin/drops/'
    | '/admin/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRouteRoute: typeof AccountRouteRouteWithChildren
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AdminPreviewRoute: typeof AdminPreviewRoute
  CareGuideRoute: typeof CareGuideRoute
  CartRoute: typeof CartRoute
  ContactRoute: typeof ContactRoute
  PrivacyRoute: typeof PrivacyRoute
  ReturnsRoute: typeof ReturnsRoute
  SizeGuideRoute: typeof SizeGuideRoute
  TermsRoute: typeof TermsRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  CheckoutSuccessRoute: typeof CheckoutSuccessRoute
  DropSlugRoute: typeof DropSlugRoute
  ShopSlugRoute: typeof ShopSlugRoute
  CheckoutIndexRoute: typeof CheckoutIndexRoute
  ShopIndexRoute: typeof ShopIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/size-guide': {
      id: '/size-guide'
      path: '/size-guide'
      fullPath: '/size-guide'
      preLoaderRoute: typeof SizeGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/returns': {
      id: '/returns'
      path: '/returns'
      fullPath: '/returns'
      preLoaderRoute: typeof ReturnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/care-guide': {
      id: '/care-guide'
      path: '/care-guide'
      fullPath: '/care-guide'
      preLoaderRoute: typeof CareGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-preview': {
      id: '/admin-preview'
      path: '/admin-preview'
      fullPath: '/admin-preview'
      preLoaderRoute: typeof AdminPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/': {
      id: '/shop/'
      path: '/shop'
      fullPath: '/shop/'
      preLoaderRoute: typeof ShopIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/': {
      id: '/checkout/'
      path: '/checkout'
      fullPath: '/checkout/'
      preLoaderRoute: typeof CheckoutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/account/': {
      id: '/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/shop/$slug': {
      id: '/shop/$slug'
      path: '/shop/$slug'
      fullPath: '/shop/$slug'
      preLoaderRoute: typeof ShopSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drop/$slug': {
      id: '/drop/$slug'
      path: '/drop/$slug'
      fullPath: '/drop/$slug'
      preLoaderRoute: typeof DropSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/success': {
      id: '/checkout/success'
      path: '/checkout/success'
      fullPath: '/checkout/success'
      preLoaderRoute: typeof CheckoutSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/auth/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/website-layout': {
      id: '/admin/website-layout'
      path: '/website-layout'
      fullPath: '/admin/website-layout'
      preLoaderRoute: typeof AdminWebsiteLayoutRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/theme': {
      id: '/admin/theme'
      path: '/theme'
      fullPath: '/admin/theme'
      preLoaderRoute: typeof AdminThemeRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/seo': {
      id: '/admin/seo'
      path: '/seo'
      fullPath: '/admin/seo'
      preLoaderRoute: typeof AdminSeoRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/media': {
      id: '/admin/media'
      path: '/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AdminMediaRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/account/personal': {
      id: '/account/personal'
      path: '/personal'
      fullPath: '/account/personal'
      preLoaderRoute: typeof AccountPersonalRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/account/addresses': {
      id: '/account/addresses'
      path: '/addresses'
      fullPath: '/account/addresses'
      preLoaderRoute: typeof AccountAddressesRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/admin/products/': {
      id: '/admin/products/'
      path: '/products'
      fullPath: '/admin/products/'
      preLoaderRoute: typeof AdminProductsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/drops/': {
      id: '/admin/drops/'
      path: '/drops'
      fullPath: '/admin/drops/'
      preLoaderRoute: typeof AdminDropsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/account/orders/': {
      id: '/account/orders/'
      path: '/orders'
      fullPath: '/account/orders/'
      preLoaderRoute: typeof AccountOrdersIndexRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/admin/products/new': {
      id: '/admin/products/new'
      path: '/products/new'
      fullPath: '/admin/products/new'
      preLoaderRoute: typeof AdminProductsNewRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/products/$productId': {
      id: '/admin/products/$productId'
      path: '/products/$productId'
      fullPath: '/admin/products/$productId'
      preLoaderRoute: typeof AdminProductsProductIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/drops/new': {
      id: '/admin/drops/new'
      path: '/drops/new'
      fullPath: '/admin/drops/new'
      preLoaderRoute: typeof AdminDropsNewRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/drops/$dropId': {
      id: '/admin/drops/$dropId'
      path: '/drops/$dropId'
      fullPath: '/admin/drops/$dropId'
      preLoaderRoute: typeof AdminDropsDropIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/account/orders/$orderId': {
      id: '/account/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/account/orders/$orderId'
      preLoaderRoute: typeof AccountOrdersOrderIdRouteImport
      parentRoute: typeof AccountRouteRoute
    }
  }
}

interface AccountRouteRouteChildren {
  AccountAddressesRoute: typeof AccountAddressesRoute
  AccountPersonalRoute: typeof AccountPersonalRoute
  AccountIndexRoute: typeof AccountIndexRoute
  AccountOrdersOrderIdRoute: typeof AccountOrdersOrderIdRoute
  AccountOrdersIndexRoute: typeof AccountOrdersIndexRoute
}

const AccountRouteRouteChildren: AccountRouteRouteChildren = {
  AccountAddressesRoute: AccountAddressesRoute,
  AccountPersonalRoute: AccountPersonalRoute,
  AccountIndexRoute: AccountIndexRoute,
  AccountOrdersOrderIdRoute: AccountOrdersOrderIdRoute,
  AccountOrdersIndexRoute: AccountOrdersIndexRoute,
}

const AccountRouteRouteWithChildren = AccountRouteRoute._addFileChildren(
  AccountRouteRouteChildren,
)

interface AdminRouteRouteChildren {
  AdminLoginRoute: typeof AdminLoginRoute
  AdminMediaRoute: typeof AdminMediaRoute
  AdminSeoRoute: typeof AdminSeoRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminThemeRoute: typeof AdminThemeRoute
  AdminWebsiteLayoutRoute: typeof AdminWebsiteLayoutRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminDropsDropIdRoute: typeof AdminDropsDropIdRoute
  AdminDropsNewRoute: typeof AdminDropsNewRoute
  AdminProductsProductIdRoute: typeof AdminProductsProductIdRoute
  AdminProductsNewRoute: typeof AdminProductsNewRoute
  AdminDropsIndexRoute: typeof AdminDropsIndexRoute
  AdminProductsIndexRoute: typeof AdminProductsIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminLoginRoute: AdminLoginRoute,
  AdminMediaRoute: AdminMediaRoute,
  AdminSeoRoute: AdminSeoRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminThemeRoute: AdminThemeRoute,
  AdminWebsiteLayoutRoute: AdminWebsiteLayoutRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminDropsDropIdRoute: AdminDropsDropIdRoute,
  AdminDropsNewRoute: AdminDropsNewRoute,
  AdminProductsProductIdRoute: AdminProductsProductIdRoute,
  AdminProductsNewRoute: AdminProductsNewRoute,
  AdminDropsIndexRoute: AdminDropsIndexRoute,
  AdminProductsIndexRoute: AdminProductsIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRouteRoute: AccountRouteRouteWithChildren,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AdminPreviewRoute: AdminPreviewRoute,
  CareGuideRoute: CareGuideRoute,
  CartRoute: CartRoute,
  ContactRoute: ContactRoute,
  PrivacyRoute: PrivacyRoute,
  ReturnsRoute: ReturnsRoute,
  SizeGuideRoute: SizeGuideRoute,
  TermsRoute: TermsRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  CheckoutSuccessRoute: CheckoutSuccessRoute,
  DropSlugRoute: DropSlugRoute,
  ShopSlugRoute: ShopSlugRoute,
  CheckoutIndexRoute: CheckoutIndexRoute,
  ShopIndexRoute: ShopIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
